spring:
  application:
    name: clinic-api

  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:my-secret-key}
  expiration: 86400000  # 24h em ms

management:
  endpoints:
    web:
      exposure:
        include: health,info